apiVersion: v1
kind: Template
metadata:
  annotations:
    description: "Create Backup of Dev Spaces Workspace PVC"
    openshift.io/display-name: "Create Backup of Dev Spaces Workspace PVC"
    template.openshift.io/bindable: "false"
    version: "1.0"
  name: workspace-backup
objects:
- apiVersion: batch/v1
  kind: Job
  metadata:
    name: ${WORKSPACE_NAME}-${WORKSPACE_NAMESPACE}-backup
  spec:
    ttlSecondsAfterFinished: 120
    selector: {}
    template:
      metadata:
        name: ${WORKSPACE_NAME}-${WORKSPACE_NAMESPACE}-backup
        annotations:
          io.kubernetes.cri-o.Devices: "/dev/fuse,/dev/net/tun"
      spec:
        hostUsers: false
        containers:
          - name: workspace-backup
            image: quay.io/cgruver0/che/workspace-backup:latest
            securityContext:
              procMount: Unmasked
            env:
            - name: WORKSPACE_NAME
              value: ${WORKSPACE_NAME}
            - name: WORKSPACE_NAMESPACE
              value: ${WORKSPACE_NAMESPACE}
            - name: WORKSPACE_REGISTRY
              value: ${WORKSPACE_REGISTRY}
            volumeMounts:
            - mountPath: /workspace-pvc
              name: workspace-pvc
        restartPolicy: Never
        volumes:
          - name: workspace-pvc
            persistentVolumeClaim:
              claimName: ${WORKSPACE_PVC}
parameters:
  -
    description: "Name of the DevWorkspace"
    displayName: "DevWorkspace Name"
    name: WORKSPACE_NAME
    required: true
  -
    description: "Name of the DevWorkspace Namespace"
    displayName: "Namespace Name"
    name: WORKSPACE_NAMESPACE
    required: true
  -
    description: "PVC for the DevWorkspace"
    displayName: "DevWorkspace PVC"
    name: WORKSPACE_PVC
    required: true
  -
    description: "Target Registry for Backup Image"
    displayName: "Backup Registry Name"
    name: WORKSPACE_REGISTRY
    required: true
    value: "nexus.clg.lab:5002/dev-spaces"
