FROM registry.access.redhat.com/ubi9:9.5

ARG USER_HOME_DIR="/home/user"
ARG WORK_DIR="/projects"
ARG INSTALL_PACKAGES="procps-ng openssl libbrotli git tar gzip zip xz unzip which shadow-utils bash zsh vi wget jq podman buildah skopeo podman-docker ca-certificates python python-pip python-devel fuse-overlayfs util-linux vim-minimal vim-enhanced helm kustomize"

ENV HOME=${USER_HOME_DIR}
ENV BUILDAH_ISOLATION=chroot
ENV REGISTRY_AUTH_FILE=/tmp/registry/auth.json

COPY --chown=0:0 entrypoint.sh /
COPY --chown=0:0 workspace-backup.sh /
COPY --chown=0:0 workspace-restore.sh /

RUN set -e ; \
  dnf install -y https://dl.fedoraproject.org/pub/epel/epel-release-latest-9.noarch.rpm ; \
  dnf install -y ${INSTALL_PACKAGES} ; \
  dnf update -y ; \
  dnf clean all ; \
  mkdir -p /usr/local/bin ; \
  mkdir -p ${WORK_DIR} ; \
  pip install -U podman-compose ; \
  pip install -U cekit ; \
  chgrp -R 0 /home ; \
  chmod -R g=u /home ${WORK_DIR} ; \
  chmod +x /entrypoint.sh ; \
  chmod +x /workspace-backup.sh ; \
  chmod +x / workspace-restore.sh ; \
  chown 0:0 /etc/passwd ; \
  chown 0:0 /etc/group ; \
  chmod g=u /etc/passwd /etc/group ; \
  # Setup for rootless podman
  setcap cap_setuid+ep /usr/bin/newuidmap ; \
  setcap cap_setgid+ep /usr/bin/newgidmap ; \
  touch /etc/subgid /etc/subuid ; \
  chown 0:0 /etc/subgid ; \
  chown 0:0 /etc/subuid ; \
  chmod -R g=u /etc/subuid /etc/subgid ; \
  # Create Sym Links for OpenShift CLI (Assumed to be retrieved by an init-container)
  ln -s /projects/bin/oc /usr/local/bin/oc ; \
  ln -s /projects/bin/kubectl /usr/local/bin/kubectl

USER 1000
WORKDIR ${WORK_DIR}
ENTRYPOINT ["/usr/libexec/podman/catatonit","--","/entrypoint.sh"]
CMD [ "tail", "-f", "/dev/null" ]